config/routes.rb
Inscriptio::Application.routes.draw do

  resources :emails do
    collection do
      get 'asset_type'
    end
  end  

  resources :school_affiliations

  resources :messages do
    collection do
      get 'help'
    end
  end  

  resources :reports

  resources :reservation_notices do
    collection do
      get 'generate_notices'
    end
  end  

  resources :statuses

  devise_for :users

  devise_scope :user do
    match "/hauthproxy/valid" => "devise/hauthproxy#valid"
    match '/hauthproxy/invalid' => 'devise/hauthproxy#invalid'
    match '/hauthproxy/logout' => 'devise/hauthproxy#sign_out', :as => :destroy_user_session
  end
  
  resources :users do
    collection do
      post 'import'
      get 'export'
    end
  end  
  
  resources :moderator_flags

  resources :posts

  resources :bulletin_boards

  resources :user_types

  resources :reservations
  
  resources :search

  resources :reservable_assets do
    member do
      get 'locate'
    end
    collection do
      post 'import'
    end
    
  end

  resources :reservable_asset_types

  resources :call_numbers
  
  resources :subject_areas

  resources :libraries do
    resources :floors do
      member do
        post 'move_higher'
        post 'move_lower'
        get 'assets'
      end
    end
  end

  root :to => 'libraries#index'

end

app/models/reservable_asset.rb
class ReservableAsset < ActiveRecord::Base
  mount_uploader :photo, AssetPhotoUploader
  
  belongs_to :floor
  belongs_to :reservable_asset_type
  has_many :reservations, :dependent => :destroy
  has_many :users, :through => :reservations
  has_one :bulletin_board, :dependent => :destroy
  
  validates_presence_of :floor_id, :name
  validates_presence_of :reservable_asset_type_id
  validates_numericality_of :min_reservation_time, :only_integer => true, :message => "can only be whole number."
  validates_numericality_of :max_reservation_time, :only_integer => true, :message => "can only be whole number."
  validates_numericality_of :max_concurrent_users, :only_integer => true, :message => "can only be whole number."
  validates_format_of :slots, :with => /^[A-Z]+(,[A-Z]+)*$/, :message => "must be in the format of 'A,B,C'", :if => Proc.new {|this| this.slots != ""}
  
  def to_s
    %Q|#{name}|
  end
  
  def max_concurrent_users
    if (!read_attribute(:max_concurrent_users).blank? && !read_attribute(:max_concurrent_users).nil?) || self.reservable_asset_type.nil?
      read_attribute(:max_concurrent_users)
    else
      ReservableAssetType.find(self.reservable_asset_type).max_concurrent_users
    end    
  end
  
  def min_reservation_time
    if (!read_attribute(:min_reservation_time).blank? && !read_attribute(:min_reservation_time).nil?) || self.reservable_asset_type.nil?
      read_attribute(:min_reservation_time)
    else
      ReservableAssetType.find(self.reservable_asset_type).min_reservation_time
    end    
  end
  
  def max_reservation_time
    if (!read_attribute(:max_reservation_time).blank? && !read_attribute(:max_reservation_time).nil?) || self.reservable_asset_type.nil?
      read_attribute(:max_reservation_time)
    else
      ReservableAssetType.find(self.reservable_asset_type).max_reservation_time
    end    
  end
  
  def slots
    if (!read_attribute(:slots).blank? && !read_attribute(:slots).nil?) || self.reservable_asset_type.nil?
      read_attribute(:slots)
    else
      ReservableAssetType.find(self.reservable_asset_type).slots
    end    
  end
  
  def current_users
    approved = Status.find(:first, :conditions => ["lower(name) = 'approved'"])
    pending = Status.find(:first, :conditions => ["lower(name) = 'pending'"])
    self.users.where('reservations.end_date > current_date') && self.users.where('reservations.status_id = ? or reservations.status_id = ?', approved, pending)
  end
  
  def current_reservations
    approved = Status.find(:first, :conditions => ["lower(name) = 'approved'"])
    pending = Status.find(:first, :conditions => ["lower(name) = 'pending'"])
    self.reservations.where('reservations.end_date > current_date') && self.reservations.where('reservations.status_id = ? or reservations.status_id = ?', approved, pending)
  end   
  
  def reservations_pending
    pending = Status.find(:first, :conditions => ["lower(name) = 'pending'"])
    self.reservations.where('reservations.end_date > current_date') && self.reservations.where('reservations.status_id = ?', pending)
  end
  
  def reservations_declined
    declined = Status.find(:first, :conditions => ["lower(name) = 'declined'"])
    self.reservations.where('reservations.end_date > current_date') && self.reservations.where('reservations.status_id = ?', declined)
  end
  
  def reservations_approved
    approved = Status.find(:first, :conditions => ["lower(name) = 'approved'"])
    self.reservations.where('reservations.end_date > current_date') && self.reservations.where('reservations.status_id = ?', approved)
  end 
  
  def reservations_waitlist
    waitlist = Status.find(:first, :conditions => ["lower(name) = 'waitlist'"])
    self.reservations.where('reservations.end_date > current_date') && self.reservations.where('reservations.status_id = ?', waitlist)
  end
  
  def reservations_recently_expired
    expired = Status.find(:first, :conditions => ["lower(name) = 'expired'"])
    year = Date.today.prev_month.month == 12 ? Date.today.prev_year.year : Date.today.year
    self.reservations.where('reservations.status_id = ?', expired) && self.reservations.where('EXTRACT(month from reservations.end_date) = ? and EXTRACT(year from reservations.end_date) = ?', Date.today.prev_month.month, year)
  end
  
  def slots_equal_users?
    (self.slots.split(',').length == self.max_concurrent_users) || (self.max_concurrent_users == 1 && self.slots.nil?)
  end
  
  def asset_full?
    self.current_users.length >= self.max_concurrent_users
  end
  
  def allow_reservation?(current_user)
    all_current = ReservableAsset.all.collect{|r| r.current_users}.flatten
    current_user_reservation = Reservation.find(:first, :conditions => ["status_id in (?) and user_id = ?", Status.find(:all, :conditions => ["lower(name) = 'approved' or lower(name) = 'pending'"]).collect{|s| s.id}, current_user.id])
    if current_user.admin
      true
    elsif self.max_concurrent_users > self.current_users.length && self.reservable_asset_type.user_types.include?(current_user.user_type)
      if current_user_reservation.nil?
        true
      elsif all_current.include?(current_user) && current_user_reservation.expiring?
        true
      else
        p "has a current reservation and not current expiring"
        false  
      end
    else
      p "not admin or asset is full or not the right user type"
      false        
    end
  end  
  
  def self.search(search)
    if search
      find(:all, :conditions => ['lower(name) LIKE ?', "%#{search}%"])
    end
  end  
end

app/models/reservable_asset_type.rb
class ReservableAssetType < ActiveRecord::Base
  mount_uploader :photo, AssetTypePhotoUploader
  
  belongs_to :library
  has_many :reservable_assets, :order => :name, :dependent => :destroy
  has_and_belongs_to_many :user_types
  has_many :reservation_notices
  
  validates_presence_of :name, :library_id, :min_reservation_time, :max_reservation_time, :max_concurrent_users, :expiration_extension_time
  validates_numericality_of :min_reservation_time, :only_integer => true, :message => "can only be whole number."
  validates_numericality_of :max_reservation_time, :only_integer => true, :message => "can only be whole number."
  validates_numericality_of :max_concurrent_users, :only_integer => true, :message => "can only be whole number."
  validates_numericality_of :expiration_extension_time, :only_integer => true, :message => "can only be whole number."
  validates_format_of :slots, :with => /^[A-Z]+(,[A-Z]+)*$/, :message => "must be in the format of 'A,B,C'", :if => Proc.new {|this| this.slots != ""}
  
  def to_s
    %Q|#{name}|
  end
  
  def slots_equal_users?
    (self.slots.split(',').length == self.max_concurrent_users) || (self.max_concurrent_users == 1 && (self.slots.nil? || self.slots.blank?))
  end  
  
end

app/controllers/reservable_assets_controller.rb
require 'csv'
class ReservableAssetsController < ApplicationController
  before_filter :authenticate_admin!, :except => [:index, :show]
  
  def index
    @reservable_assets = ReservableAsset.all
    @libraries = Library.all
  end

  def new
    @reservable_asset = ReservableAsset.new
    @library = Library.find(params[:library])
  end

  def show
    @reservable_asset = ReservableAsset.find(params[:id])
    
    breadcrumbs.add @reservable_asset.floor.library.name, library_path(@reservable_asset.floor.library.id)
    breadcrumbs.add @reservable_asset.floor.name, library_floor_path(@reservable_asset.floor.library.id,@reservable_asset.floor.id)
    breadcrumbs.add @reservable_asset.name, @reservable_asset.id
  end

  def edit
    @reservable_asset = ReservableAsset.find(params[:id])
  end
  
  def create
    @reservable_asset = ReservableAsset.new
  
    @reservable_asset.attributes = params[:reservable_asset]
    respond_to do|format|
      
      if @reservable_asset.slots_equal_users?
        if @reservable_asset.save
          if @reservable_asset.reservable_asset_type.has_bulletin_board
            @bulletin_board = BulletinBoard.new
            @bulletin_board.reservable_asset = @reservable_asset
            @bulletin_board.post_lifetime = 30
            @bulletin_board.save!
          end  
          flash[:notice] = 'Added that Reservable Asset'
          format.html {render :action => :show}
        else
          flash[:error] = 'Could not add that Reservable Asset'
          format.html {render :action => :new}
        end
      else
        flash[:error] = 'Number of slots does not match number of concurrent users.'
        format.html {render :action => :new}    
      end
      
    end
  end

  def destroy
    @reservable_asset = ReservableAsset.find(params[:id])
    reservable_asset = @reservable_asset.id
    if @reservable_asset.destroy
      flash[:notice] = %Q|Deleted reservable asset #{reservable_asset}|
      redirect_to :action => :index
    end
  end

  def update
    @reservable_asset = ReservableAsset.find(params[:id])
    @reservable_asset.attributes = params[:reservable_asset]
    respond_to do|format|
      
      if @reservable_asset.slots_equal_users?
        if @reservable_asset.save
          flash[:notice] = %Q|#{@reservable_asset} updated|
          format.html {render :action => :show}
        else
          flash[:error] = 'Could not update that Reservable Asset'
          format.html {render :action => :new}
        end
      else
        flash[:error] = 'Number of slots does not match number of concurrent users.'
        format.html {render :action => :new}    
      end
      
    end
  end

  def locate
    @reservable_asset = ReservableAsset.find(params[:id])
    @reservable_asset.x1 = params[:reservable_asset][:x1]
    @reservable_asset.y1 = params[:reservable_asset][:y1]
    @reservable_asset.x2 = params[:reservable_asset][:x2]
    @reservable_asset.y2 = params[:reservable_asset][:y2]
    respond_to do|format|
      if @reservable_asset.save
        flash[:notice] = %Q|#{@reservable_asset} updated|
        format.html {render :action => :show}
      else
        flash[:error] = 'Could not update that Reservable Asset'
        format.html {render :action => :new}
      end
    end
  end
  
  def import
    @file = params[:upload][:datafile] unless params[:upload].blank?
    CSV.parse(@file.read).each do |cell|

        floor = Floor.find(cell[0].to_i)
        asset_type = ReservableAssetType.find(cell[1].to_i)
        
        asset={}
        
        asset[:floor] = floor
        asset[:reservable_asset_type] = asset_type
        asset[:name] = cell[2]
        asset[:description] = cell[3]
        asset[:location] = cell[4]
        asset[:min_reservation_time] = cell[5]
        asset[:max_reservation_time] = cell[6]
        asset[:max_concurrent_users] = cell[7]
        asset[:slots] = cell[8]
        asset[:access_code] = cell[9]
        asset[:notes] = cell[10]
        
        @reservable_asset = ReservableAsset.new
 
        @reservable_asset.attributes = asset
    
        if @reservable_asset.save
          if @reservable_asset.reservable_asset_type.has_bulletin_board
            @bulletin_board = BulletinBoard.new
            @bulletin_board.reservable_asset = @reservable_asset
            @bulletin_board.post_lifetime = "1 month"
            @bulletin_board.save!
          end
        end
    end
    redirect_to reservable_asset_types_path
  end  
end

app/helpers/reservable_assets_helper.rb
module ReservableAssetsHelper
end

app/views/reservable_assets/edit.html.erb
<div class="reservable_asset edit_object">
  <%= render :partial => 'shared/forms/reservable_asset' %>
</div>

app/views/reservable_assets/index.html.erb
<% content_for :header do %>Reservable Assets<% end %>
<div class="reservable_assets collection-list">
  <% unless @reservable_assets.blank? %>
    <%= render :partial => 'shared/lines/reservable_asset', :collection => @reservable_assets %>
  <% else %>
    <h2>No reservable assets for this floor yet.</h2>
  <% end %>
  <% if current_user.admin? %>
    <h2 class="action-button"><%= link_to('New Reservable Asset', new_reservable_asset_path) %></h2>
  <% end %>  
</div>

<div class="asset_upload">
  <h2>Batch Upload</h2>	

    <h3>Import choices via CSV</h3>

    <p>
      Use the form below to import choices via a CSV (comma separated value) file. All 11 fields must be present even if they are left blank.
      Do not use column headings or quotes around text in any field. Each row will be separated by a new line or carriage return.
    </p>
    <p>
      These are the fields to be populated:
	  <ul>
		<li>floor id</li>
		<li>asset type id</li>
		<li>name</li>
		<li>description</li>
		<li>location</li>
		<li>minimum reservation time (in days)*</li>
		<li>maximum reservation time (in days)*</li>
		<li>maximum concurrent users*</li>
		<li>reservation time increment (in days)*</li>
		<li>access code</li>
		<li>notes</li>
	  </ul>
    </p>
	<p>
	  *If these fields are left blank, the values will be inherited from those indicated on the reservable asset type.
	</p>
    <p>
	  e.g. floor id, asset type id, name, description, location, min reservation time, max reservation time, max concurrent users, reservation time       increment, access code, notes
    </p>

  <p>
    <b><i>Format example:</i></b><br />

    <code>
      2,1,CA1,carrel description,NW corner,7,90,3,7,codeA,these are some notes<br />
      3,1,CA2,carrel description,South side of floor,,,,,codeB,these are some notes<br />
      2,1,CA3,carrel description,Near the restrooms,,,,,codeC,these are some notes<br />
      1,1,CA4,carrel description,Near the stairs,,,,,codeD,these are some notes<br />
    </code>

</p>
  <%= form_tag import_reservable_assets_path, :multipart => true do -%>
    <%= file_field 'upload', 'datafile' %></p>
	<%= submit_tag "Upload", :disable_with => 'Uploading...' %>
  <% end -%>
</div>	

app/views/reservable_assets/new.html.erb
<h2>New Reservable Asset</h2>
<div class="reservable_asset new_object">
  <%= render :partial => 'shared/forms/reservable_asset' %>
</div>

app/views/reservable_assets/show.html.erb
<% content_for :header do %><%= @reservable_asset.reservable_asset_type.name %> on <%= link_to @reservable_asset.floor.name, library_floor_path(@reservable_asset.floor.library,@reservable_asset.floor) %><% end %>

<h2 class="collapsable reservable_asset_description"><%= @reservable_asset.reservable_asset_type.name %> <%= @reservable_asset.name %> Info</h2>

<div class="navlist reservable_asset_description reservable_asset_description-target">
  <dl>
    <dt>Description:</dt>
      <dd><%= @reservable_asset.description %></dd>
    <dt>Location:</dt>
      <dd><%= @reservable_asset.location %></dd>
    <dt>Minimum Reservation Time:</dt>
      <dd><%= @reservable_asset.min_reservation_time %></dd>
    <dt>Maximum Reservation Time:</dt>
      <dd><%= @reservable_asset.max_reservation_time %></dd>
    <dt>Maximum Concurrent Users:</dt>
      <dd><%= @reservable_asset.max_concurrent_users %></dd>
    <dt>Slots:</dt>
      <dd><%= @reservable_asset.slots %></dd>
    <dt>Seats Available:</dt>
      <dd><%= @reservable_asset.max_concurrent_users - @reservable_asset.current_users.length %></dd>
	<% if current_user.admin? %>
	  <dt>Access Code:</dt>
        <dd><%= @reservable_asset.access_code %></dd>
	<% end %>
	<% unless @reservable_asset.bulletin_board.nil? %>
      <% if @reservable_asset.current_users.include?(current_user) || current_user.admin? %>
	    <dt>Bulletin Board</dt>
        <dd><%= link_to "Access Board", bulletin_board_path(@reservable_asset.bulletin_board) %></dd>
	  <% end %>	
    <% end %>	
	<dt>Notes:</dt>
	  <% unless @reservable_asset.notes.blank? %>
        <dd><%= @reservable_asset.notes %></dd>
	  <% else %>
		<dd>None</dd>
	  <% end %>	
  </dl>
	
  <% unless @reservable_asset.photo.blank? %>
    <h2>Photo</h2>
    <%= image_tag(@reservable_asset.photo.url) %>
  <% end %>

  <% if @reservable_asset.allow_reservation?(current_user) %>
    <h2 class="action-reserve-asset"><%= link_to('Reserve This Asset', new_reservation_path(:reservable_asset => @reservable_asset)) %></h2>
  <% else %>
	<h3>You are not able to reserve this asset at this time.</h3>
  <% end %>
</div>


  <% if current_user.admin? %>
    <% unless @reservable_asset.reservations.blank? %>
      <% unless @reservable_asset.reservations_approved.blank? %>
	    <h2 class="collapsable reservable_asset_approved">Approved Reservations - <%= @reservable_asset.reservations_approved.count %></h2>
   	    <div class="navlist reservable_asset_approved reservable_asset_approved-target">
	      <%= render :partial => 'shared/lines/reservation', :collection => @reservable_asset.reservations_approved %>
	    </div>
	  <% end %>
	  <% unless @reservable_asset.reservations_pending.blank? %>
	    <h2 class="collapsable reservable_asset_pending">Pending Reservations - <%= @reservable_asset.reservations_pending.count %></h2>
   	    <div class="navlist reservable_asset_pending reservable_asset_pending-target">
	      <%= render :partial => 'shared/lines/reservation', :collection => @reservable_asset.reservations_pending %>
	    </div>
	  <% end %>
	  <% unless @reservable_asset.reservations_declined.blank? %>
	    <h2 class="collapsable reservable_asset_declined">Declined Reservations - <%= @reservable_asset.reservations_declined.count %></h2>
   	    <div class="navlist reservable_asset_declined reservable_asset_declined-target">
	      <%= render :partial => 'shared/lines/reservation', :collection => @reservable_asset.reservations_declined %>
	    </div>
	  <% end %>
	  <% unless @reservable_asset.reservations_waitlist.blank? %>
        <h2 class="collapsable reservable_asset_waitlist">Waitlist Reservations - <%= @reservable_asset.reservations_waitlist.count %></h2>
   	    <div class="navlist reservable_asset_waitlist reservable_asset_waitlist-target">
	      <%= render :partial => 'shared/lines/reservation', :collection => @reservable_asset.reservations_waitlist %>
	    </div>
	  <% end %>
    <% else %>
      <h2>No reservations for this asset yet.</h2>
    <% end %>
  <% end %>