config/routes.rb
Inscriptio::Application.routes.draw do

  resources :emails do
    collection do
      get 'asset_type'
    end
  end  

  resources :school_affiliations

  resources :messages do
    collection do
      get 'help'
    end
  end  

  resources :reports

  resources :reservation_notices do
    collection do
      get 'generate_notices'
    end
  end  

  resources :statuses

  devise_for :users

  devise_scope :user do
    match "/hauthproxy/valid" => "devise/hauthproxy#valid"
    match '/hauthproxy/invalid' => 'devise/hauthproxy#invalid'
    match '/hauthproxy/logout' => 'devise/hauthproxy#sign_out', :as => :destroy_user_session
  end
  
  resources :users do
    collection do
      post 'import'
      get 'export'
    end
  end  
  
  resources :moderator_flags

  resources :posts

  resources :bulletin_boards

  resources :user_types

  resources :reservations
  
  resources :search

  resources :reservable_assets do
    member do
      get 'locate'
    end
    collection do
      post 'import'
    end
    
  end

  resources :reservable_asset_types

  resources :call_numbers
  
  resources :subject_areas

  resources :libraries do
    resources :floors do
      member do
        post 'move_higher'
        post 'move_lower'
        get 'assets'
      end
    end
  end

  root :to => 'libraries#index'

end

app/models/library.rb
class Library < ActiveRecord::Base
  has_many :floors, :dependent => :destroy, :order => :position
  has_many :reservable_asset_types, :dependent => :destroy
  has_many :reservation_notices

  validates_presence_of :name, :address_1, :city, :state, :zip, :from
  validates_format_of :url, :with => /^https?:\/\//, :allow_blank => true
  validates_format_of :from, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_format_of :bcc, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :allow_blank => true
  validates_length_of :description, :contact_info, :maximum => 16.kilobytes, :allow_blank => true

  def to_s
    %Q|#{name}|
  end
  
  def self.search(search)
    if search
      find(:all, :conditions => ['lower(name) LIKE ?', "%#{search}%"])
    end
  end
  
  def bcc_list
    self.bcc.split(',')
  end  
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_filter :authenticate_admin!, :only => [:new, :create, :edit, :update, :destroy]

  def index
    @libraries = Library.all
    @assets = ReservableAssetType.all
    @welcome_message = Message.find(:first, :conditions => ["title LIKE ?", '%Welcome%'])
    if @welcome_message.nil?
      @message = Message.new
    end    
  end

  def new
    @library = Library.new
  end

  def create
    @library = Library.new
    @library.attributes = params[:library]
    respond_to do|format|
      if @library.save
        flash[:notice] = 'Added that library'
        format.html { render :action => :show }
      else 
        flash[:error] = 'Could not create that library'
        format.html { render :action => :new }
      end
    end
  end

  def edit
    @library = Library.find(params[:id])
  end

  def update
    @library = Library.find(params[:id])
    @library.attributes = params[:library]
    respond_to do|format|
      if @library.save
        flash[:notice] = %Q|#{@library} updated|
        format.html {render :action => :show}
      else
        flash[:error] = 'Could not update that library'
        format.html {render :action => :new}
      end
    end
  end

  def show
    @library = Library.find(params[:id])
    @subject_areas = []
    @library.floors.collect{|f| @subject_areas << f.subject_areas}
    @subject_areas.flatten!
    
    breadcrumbs.add @library.name, @library.id
  end

  def destroy
    @library = Library.find(params[:id])
    library_name = @library.name
    if @library.destroy
      flash[:notice] = %Q|Deleted #{library_name}|
      redirect_to :action => :index
    end
  end

end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/edit.html.erb
<div class="library edit_object">
  <%= render :partial => 'shared/forms/library' %>
</div>

app/views/libraries/index.html.erb
<% content_for :header do %>Libraries<% end %>
<div>	
  <h2><%= display_message(:welcome).title %></h2>
  <p>  
    <%= raw display_message(:welcome).content %>
  </p>
  <% if current_user.admin? %>
    <%= link_to('Edit', edit_message_path(display_message(:welcome)), :class => "action-edit") %>
  <% end %>

  <% unless @libraries.blank? %>
    <p>
	  Assets include:
	  <ul>
	  <% @libraries.each do |library| %>
	    <li>
	      <%= library.name %>: 	
	      <% library.reservable_asset_types.each do |asset| %>
		    <%= asset.name %> <%= current_user.try(:admin?) ? "(ID #{asset.id})" : "" %>
		    <% if !(library.reservable_asset_types.last == asset) %>
		      <%= ", " %>
		    <% end %>
	      <% end %>    
	    </li>
	  <% end %>
	  </ul>	
    </p>	
  <% end %> 	
</div>

<div class="libraries collection-list">
  <% unless @libraries.blank? %>
    <%= render :partial => 'shared/lines/library', :collection => @libraries %>
  <% else %>
    <h2>No libraries yet.</h2>
  <% end %>
  <% if current_user.admin? %>
    <h2 class="action-new-library"><%= link_to('New Library', new_library_path) %></h2>
  <% end %>
</div>

app/views/libraries/new.html.erb
<h2>New Library</h2>
<div class="library new_object">
  <%= render :partial => 'shared/forms/library' %>
</div>

app/views/libraries/show.html.erb
<% content_for :body do %>class="double-column"<% end %>
<% content_for :header do %><%= link_to(@library.name, @library.url, :class=> 'external_link', :target => "_blank" ) %><% end %>

<% content_for :content_left do %>
  <h4 class="collapsable description">About</h2>
  <div class="description description-target">
    <%= raw @library.description %>
  </div>

  <h4 class="collapsable address">Address</h2>
  <div class="address-target vcard">
    <%= render :partial => 'shared/microformats/adr', :object => @library %>
  </div>

  <h4 class="collapsable contact_info">Contact</h2>
  <div class="contact_info contact_info-target">
	<%= raw @library.contact_info %>
  </div>

  <h4 class="collapsable tos">Terms of Service</h2>
  <div class="tos tos-target">
	<%= raw @library.tos %>
  </div>
<% end %>

<h2>Floors</h2>
<% unless @library.floors.blank? %>
  <%= render :partial => 'shared/lines/floor', :collection => @library.floors %>
<% else %>
  <h4>No floors yet.</h4>
<% end %>
<% if current_user.admin? %>
  <h2 class="action-new-floor"><%= link_to('New Floor', new_library_floor_path(@library)) %></h2>
<% end %>

<h2>All Subject Areas</h2>

<% unless @subject_areas.blank? %>
  <%= render :partial => 'shared/lines/subject_area', :collection => @subject_areas %>
<% else %>
  <h4>No subject areas yet.</h4>
<% end %>
<% if current_user.admin? %>
  <h2 class="action-new-subject"><%= link_to('New Subject Area', new_subject_area_path) %></h2>
<% end %>
<!-- </div> -->