config/routes.rb
Inscriptio::Application.routes.draw do

  resources :emails do
    collection do
      get 'asset_type'
    end
  end  

  resources :school_affiliations

  resources :messages do
    collection do
      get 'help'
    end
  end  

  resources :reports

  resources :reservation_notices do
    collection do
      get 'generate_notices'
    end
  end  

  resources :statuses

  devise_for :users

  devise_scope :user do
    match "/hauthproxy/valid" => "devise/hauthproxy#valid"
    match '/hauthproxy/invalid' => 'devise/hauthproxy#invalid'
    match '/hauthproxy/logout' => 'devise/hauthproxy#sign_out', :as => :destroy_user_session
  end
  
  resources :users do
    collection do
      post 'import'
      get 'export'
    end
  end  
  
  resources :moderator_flags

  resources :posts

  resources :bulletin_boards

  resources :user_types

  resources :reservations
  
  resources :search

  resources :reservable_assets do
    member do
      get 'locate'
    end
    collection do
      post 'import'
    end
    
  end

  resources :reservable_asset_types

  resources :call_numbers
  
  resources :subject_areas

  resources :libraries do
    resources :floors do
      member do
        post 'move_higher'
        post 'move_lower'
        get 'assets'
      end
    end
  end

  root :to => 'libraries#index'

end

app/models/call_number.rb
class CallNumber < ActiveRecord::Base
  has_and_belongs_to_many :floors, :order => :name
  belongs_to :subject_area

  validates_presence_of :call_number
  validates_uniqueness_of :call_number
  validates_length_of :call_number, :minimum => 1, :maximum => 50

  validates_length_of :description, :maximum => 16.kilobytes, :allow_blank => true
  has_many :libraries, :through => :floors

  def to_s
    "#{call_number}"
  end
  
  def self.search(search)
    if search
      find(:all, :conditions => ['lower(call_number) LIKE ? or lower(long_name) LIKE ?', "%#{search}%", "%#{search}%"])
    end
  end

end

app/controllers/call_numbers_controller.rb
class CallNumbersController < ApplicationController
  before_filter :authenticate_admin!, :except => [:index, :show]

  def index
    @call_numbers = CallNumber.all
    
    breadcrumbs.add "Call Numbers"
  end

  def new
    @call_number = CallNumber.new
    
    breadcrumbs.add 'Call Numbers', call_numbers_path
    breadcrumbs.add 'New'
  end

  def show
    @call_number = CallNumber.find(params[:id])
    
    breadcrumbs.add @call_number.subject_area.name, subject_area_path(@call_number.subject_area.id)
    breadcrumbs.add @call_number.call_number, @call_number.id
  end

  def create
    @call_number = CallNumber.new
    @call_number.attributes = params[:call_number]
    respond_to do|format|
      if @call_number.save
        flash[:notice] = 'Added that Call Number'
        format.html {render :action => :show}
      else
        flash[:error] = 'Could not add that Call Number'
        format.html {render :action => :new}
      end
    end
  end

  def destroy
    @call_number = CallNumber.find(params[:id])
    call_number = @call_number.call_number
    if @call_number.destroy
      flash[:notice] = %Q|Deleted call number #{call_number}|
      redirect_to :action => :index
    end
  end

  def edit
    @call_number = CallNumber.find(params[:id])
    
    breadcrumbs.add 'Call Numbers', call_numbers_path
    breadcrumbs.add 'Edit'
  end

  def update
    @call_number = CallNumber.find(params[:id])
    @call_number.attributes = params[:call_number]
    respond_to do|format|
      if @call_number.save
        flash[:notice] = %Q|#{@call_number} updated|
        format.html {render :action => :show}
      else
        flash[:error] = 'Could not update that Call Number'
        format.html {render :action => :new}
      end
    end
  end

end

app/helpers/call_numbers_helper.rb
module CallNumbersHelper
end

app/views/call_numbers/edit.html.erb
<div class="call_number edit_object">
  <%= render :partial => 'shared/forms/call_number' %>
</div>

app/views/call_numbers/index.html.erb
<div class="call_numbers collection-list">
  <% unless @call_numbers.blank? %>
    <%= render :partial => 'shared/lines/call_number', :collection => @call_numbers %>
  <% else %>
    <h2>No call numbers yet.</h2>
  <% end %>
</div>


  <% if current_user.admin? %>
    <h2 class="action-button"><%= link_to('New Call Number', new_call_number_path) %></h2>
  <% end %>

app/views/call_numbers/new.html.erb
<h2>New Call Number</h2>

<div class="call_number new_object">
  <%= render :partial => 'shared/forms/call_number' %>
</div>

app/views/call_numbers/show.html.erb
<div class="call_number show-object">
  <% content_for :header do %><%= @call_number %><% end %>
  <dl>
	<dt>Long Name:</dt>
    <dd><%= @call_number.long_name %></dd>
    <dt>Description:</dt>
    <dd><%= @call_number.description %></dd>
    <dt>Floors:</dt>
    <dd><%= @call_number.floors.join(', ') %></dd>
    <dt>Subject Area:</dt>
    <dd><%= link_to @call_number.subject_area, subject_area_path(@call_number.subject_area.id) %></dd>
  </dl>
</div>