config/routes.rb
Inscriptio::Application.routes.draw do

  resources :emails do
    collection do
      get 'asset_type'
    end
  end  

  resources :school_affiliations

  resources :messages do
    collection do
      get 'help'
    end
  end  

  resources :reports

  resources :reservation_notices do
    collection do
      get 'generate_notices'
    end
  end  

  resources :statuses

  devise_for :users

  devise_scope :user do
    match "/hauthproxy/valid" => "devise/hauthproxy#valid"
    match '/hauthproxy/invalid' => 'devise/hauthproxy#invalid'
    match '/hauthproxy/logout' => 'devise/hauthproxy#sign_out', :as => :destroy_user_session
  end
  
  resources :users do
    collection do
      post 'import'
      get 'export'
    end
  end  
  
  resources :moderator_flags

  resources :posts

  resources :bulletin_boards

  resources :user_types

  resources :reservations
  
  resources :search

  resources :reservable_assets do
    member do
      get 'locate'
    end
    collection do
      post 'import'
    end
    
  end

  resources :reservable_asset_types

  resources :call_numbers
  
  resources :subject_areas

  resources :libraries do
    resources :floors do
      member do
        post 'move_higher'
        post 'move_lower'
        get 'assets'
      end
    end
  end

  root :to => 'libraries#index'

end

app/controllers/reservable_asset_types_controller.rb
class ReservableAssetTypesController < ApplicationController
  before_filter :authenticate_admin!, :except => [:index, :show]
  
  def index
    @libraries = Library.all
    
    breadcrumbs.add 'Reservable Assets'
  end

  def new
    @reservable_asset_type = ReservableAssetType.new
  end

  def show
    @reservable_asset_type = ReservableAssetType.find(params[:id])
  end

  def edit
    @reservable_asset_type = ReservableAssetType.find(params[:id])
  end
  
  def create
    @reservable_asset_type = ReservableAssetType.new
    @reservable_asset_type.attributes = params[:reservable_asset_type]
    respond_to do|format|
      if @reservable_asset_type.slots_equal_users?
        if @reservable_asset_type.save
          flash[:notice] = 'Added that Reservable Asset Type'
          format.html {render :action => :show}
        else
          flash[:error] = 'Could not add that Reservable Asset Type'
          format.html {render :action => :new}
        end
      else
        flash[:error] = 'Number of slots does not match number of concurrent users.'
        format.html {render :action => :new}    
      end
    end
  end

  def destroy
    @reservable_asset_type = ReservableAssetType.find(params[:id])
    reservable_asset_type = @reservable_asset_type.name
    if @reservable_asset_type.destroy
      flash[:notice] = %Q|Deleted reservable asset type #{reservable_asset_type}|
      redirect_to :action => :index
    else

    end
  end

  def update
    @reservable_asset_type = ReservableAssetType.find(params[:id])
    @reservable_asset_type.attributes = params[:reservable_asset_type]
    respond_to do|format|
      if @reservable_asset_type.slots_equal_users?
        if @reservable_asset_type.save
          flash[:notice] = %Q|#{@reservable_asset_type} updated|
          format.html {render :action => :show}
        else
          flash[:error] = 'Could not update that Reservable Asset Type'
          format.html {render :action => :new}
        end
      else
        flash[:error] = 'Number of slots does not match number of concurrent users.'
        format.html {render :action => :new}    
      end
    end
  end
end

app/helpers/reservable_asset_types_helper.rb
module ReservableAssetTypesHelper
end

app/views/reservable_asset_types/edit.html.erb
<div class="reservable_asset_type edit_object">
  <%= render :partial => 'shared/forms/reservable_asset_type' %>
</div>

app/views/reservable_asset_types/index.html.erb
<% content_for :header do %>Reservable Assets<% end %>
<div class="reservable_asset_types collection-list">
  <% unless @libraries.blank? %>
    <% if current_user.admin? %>
      <h2 class="action-new-asset-type"><%= link_to('New Reservable Asset Type', new_reservable_asset_type_path) %></h2>
    <% end %>
	<% @libraries.each do |library| %>
	  <h2><%= library.name %></h2>
	  <% if current_user.admin? %>
	    <h3 class="collapsable email_all">Email All in <%= library %></h3>
	    <div class="email_all email_all-target">
		  <p>
			<% form_tag new_email_path, :method => 'get' do %>
			  <%= text_field_tag :subject %><br />
			  <%= text_area_tag :content, nil, :rows => 10, :cols => 35 %><br />
			  <%= hidden_field_tag :library, library.id %>  
			  <%= submit_tag "Send", :name => nil %>
			<% end %>
	      </p>
	    </div>
      <% end %>
      <% unless library.reservable_asset_types.blank? %>
        <h3>Assets</h3>
        <%= render :partial => 'shared/lines/reservable_asset_type', :collection => library.reservable_asset_types %>
      <% else %>
        <h3>No reservable asset types for this library yet.</h3>
      <% end %>
    <% end %>
	
  <% end %>
</div>

<h2 class="collapsable asset_upload">Batch Upload</h2>

<div class="asset_upload asset_upload-target">

    <h3>Import Assets via CSV</h3>

    <p>
      Use the form below to import assets via a CSV (comma separated value) file. All 11 fields must be present even if they are left blank.
      Do not use column headings or quotes around text in any field. Each row will be separated by a new line or carriage return.
    </p>
    <p>
      These are the fields to be populated with the assumption that you are using a spreadsheet application like Excel:
	  <ul>
		<li>(Column A) floor id</li>
		<li>(Column B) asset type id</li>
		<li>(Column C) name</li>
		<li>(Column D) description</li>
		<li>(Column E) location</li>
		<li>(Column F) minimum reservation time (in days)*</li>
		<li>(Column G) maximum reservation time (in days)*</li>
		<li>(Column H) maximum concurrent users*</li>
		<li>(Column I) slots*</li>
		<li>(Column J) access code</li>
		<li>(Column K) notes</li>
	  </ul>
    </p>
	<p>
	  *If these fields are left blank, the values will be inherited from those indicated on the reservable asset type.
	</p>
	<p>
	  Please note that the 'slots' field will depend on the count of max users. For example, if an asset has max concurrent users of 4 then in column I you will put A,B,C,D. If the max concurrent users is 3 you will put A,B,C, if it is 1 then you can either leave it blank or put A.
	</p>
    <p>
	  e.g. floor id, asset type id, name, description, location, min reservation time, max reservation time, max concurrent users, slots, access code, notes
    </p>

  <%= form_tag import_reservable_assets_path, :multipart => true do -%>
    <%= file_field 'upload', 'datafile' %></p>
	<%= submit_tag "Upload", :disable_with => 'Uploading...' %>
  <% end -%>
</div>	

app/views/reservable_asset_types/new.html.erb
<h2>New Reservable Asset Type</h2>
<div class="reservable_asset_type new_object">
  <%= render :partial => 'shared/forms/reservable_asset_type' %>
</div>

app/views/reservable_asset_types/show.html.erb
<div class="reservable_asset_type show-object">
      <% content_for :header do %><%= @reservable_asset_type.name %> in <%= link_to @reservable_asset_type.library.name, @reservable_asset_type.library %><% end %>
  <dl>
    <dt>Minimum Reservation Time:</dt>
      <dd><%= @reservable_asset_type.min_reservation_time %></dd>
	<dt>Maximum Reservation Time:</dt>
      <dd><%= @reservable_asset_type.max_reservation_time %></dd>
	<dt>Maximum Concurrent Users:</dt>
      <dd><%= @reservable_asset_type.max_concurrent_users %></dd>
    <dt>Slots:</dt>
      <dd><%= @reservable_asset_type.slots %></dd>
	<dt>Has Access Code:</dt>
      <dd><%= @reservable_asset_type.has_code %></dd>
	<dt>Requires Moderation:</dt>
      <dd><%= @reservable_asset_type.require_moderation %></dd>
    <dt>Welcome Message:</dt>
      <dd><%= @reservable_asset_type.welcome_message %></dd>
	<dt>Expiration Extension Time:</dt>
      <dd><%= @reservable_asset_type.expiration_extension_time %></dd>
	<dt>Has Bulletin Board:</dt>
      <dd><%= @reservable_asset_type.has_bulletin_board %></dd>
	<dt>User Types:</dt>
	<% unless @reservable_asset_type.user_types.blank? %>
	  <% @reservable_asset_type.user_types.each do |ut| %>
	    <dd><%= ut.name %></dd>
	  <% end %>
	<% end %>
  </dl>
	
	<% unless @reservable_asset_type.photo.blank? %>
	  <h2>Photo</h2>
      <%= image_tag(@reservable_asset_type.photo.url) %>
    <% end %>

	<% if current_user.admin? %>
	  <%= link_to('Edit', edit_reservable_asset_type_path(@reservable_asset_type), :class => "action-edit") %> |
	  <%= link_to('Delete', reservable_asset_type_path(@reservable_asset_type), :confirm => "Are you sure you want to delete this item? This action cannot be undone.", :method => :delete, :id => "delete-#{@reservable_asset_type.id}", :class => "action-delete") %>
	<% end %>
</div>